
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 08 18:57:11 CEST 2014
//----------------------------------------------------

package fr.ul.compilation.plic0.analyser;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 20;
  public static final int EGAL = 9;
  public static final int PARO = 6;
  public static final int CHAINE = 21;
  public static final int PLUS = 4;
  public static final int LIRE = 14;
  public static final int STATUT = 23;
  public static final int INFERIEUR = 8;
  public static final int SEMI = 12;
  public static final int ECRIRE = 13;
  public static final int SUPERIEUR = 10;
  public static final int PARF = 7;
  public static final int DIFFERENT = 11;
  public static final int FIN_CLASSE = 17;
  public static final int MOINS = 3;
  public static final int TYPE = 16;
  public static final int ENTIER = 19;
  public static final int EOF = 0;
  public static final int MULTIPLICATION = 5;
  public static final int IDF_MUL = 22;
  public static final int error = 1;
  public static final int UMOINS = 2;
  public static final int CLASSE = 18;
  public static final int EGAL_AFFECT = 15;
}

