
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 07 20:11:42 CEST 2014
//----------------------------------------------------

package fr.ul.compilation.plic0.analyser;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int INFERIEUR = 8;
  public static final int PARO = 6;
  public static final int DIFFERENT = 11;
  public static final int EOF = 0;
  public static final int PLUS = 4;
  public static final int EGAL = 9;
  public static final int ENTIER = 12;
  public static final int error = 1;
  public static final int PARF = 7;
  public static final int MOINS = 3;
  public static final int SUPERIEUR = 10;
  public static final int UMOINS = 2;
  public static final int MULTIPLICATION = 5;
}

