
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 04 16:48:25 CEST 2014
//----------------------------------------------------

package fr.ul.compilation.plic1.analyser;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int RETOURNE = 22;
  public static final int IDF = 27;
  public static final int EGAL = 9;
  public static final int PTVIRG = 12;
  public static final int CLASS = 19;
  public static final int CHAINE = 24;
  public static final int PLUS = 4;
  public static final int LIRE = 15;
  public static final int INFERIEUR = 8;
  public static final int ECRIRE = 14;
  public static final int PRIV = 26;
  public static final int SUPERIEUR = 10;
  public static final int DIFFERENT = 11;
  public static final int MOINS = 3;
  public static final int PARFER = 7;
  public static final int HERITE = 20;
  public static final int ENTIER = 23;
  public static final int EOF = 0;
  public static final int VIRG = 13;
  public static final int MULTIPLICATION = 5;
  public static final int DEB = 18;
  public static final int error = 1;
  public static final int UMOINS = 2;
  public static final int PUB = 25;
  public static final int PAROUV = 6;
  public static final int EGAL_AFFECT = 16;
  public static final int FIN = 17;
  public static final int ENT = 21;
}

